# -*- coding: utf-8 -*-
"""assignment1_sol.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-uSoFi_HiHQ02hTQk9u6tMIIYPJmupa

# DA231 - Data Engineering at Scale

# Assignment 1 : Spark Dataframes

## Posted on: 15<sup>th</sup> September 2025
## Deadline: <del>6<sup>th</sup> October 2025</del> 8<sup>th</sup> October 2025 11:59 PM
## Maximum Points: 150

### Changelog:
----
* v0.1: Initial release of questions. [KA, ST, YS]
* v1.1: [KA, ST]
    1.   Update in *Q1.2* regarding escape sequences to be removed and replacement by a whitespace.
    2.   Added instruction in *Q4.1* to convert all text to lowercase.
    3.   Update in *Q5*: Added chunk selection and refactored it into two subquestions.
    4.   Clarification in *Q2.2* to include subwords for the count



### Common Instructions
----



* You must ONLY edit cells and regions within those cells that allow changes. **DO NOT MODIFY other cells**. This can cause the evaluation script to break and you **WILL** be penalized or get **ZERO** points.
* You MUST NOT use the string **###!@** anywhere in your code or comments. We will be using this special substring for pattern matching during evaluations.
* You may declare **all** your valid imports and user-defined functions in the cells that are provided. Otherwise, all parts of your answer must remain between the space provided for the solution to each question.
* You must only use transformations and actions over Spark DataFrames and Spark SQL to solve the assignment (**Spark Core**). You **MUST NOT** use Spark RDDs, MLLib, etc, unless specified.
 <!-- * https://spark.apache.org/docs/latest/api/python/reference/pyspark.html#rdd-apis -->
* Most of your processing to solve the problem should be done **within Spark**. Minimal post processing may be done in the Python driver code.
* You **must not** use Numpy, Scipy, etc. within the **driver** code. But you may use standard Python libraries as part of lambda expressions or functions passed to Spark transformations and actions.
<!-- * You must not use the default statistics operation (RDD.stats()) available in the **Spark Numeric RDD**. -->
* Our evaluations will include **alternate input test cases** dataset that have the same format but different contents/sizes.
* We will provide **reference outputs** for the test inputs. You can use these to verify the correctness of your solutions.<br>
**NOTE (Trigger Warning):** *The assignment involves dataset which contains sensitive words. Kindly take care when processing this data as it has sensitive words that are (by definition) not polite and potentially upsetting.*
<br>

### **IMPORTANT:** Academic Integrity
----
 The assignment must be completed by yourself without any assistance from others or from online sources, ChatGPT, Copilot, etc. Taking online help for standard API references or clearing simple doubts on Python/Spark is allowed. If **any cases of plagiarism are detected, you may get a failing grade in the course and/or be reported to the Institute and your parent Organization for further action**. Please follow IISc’s Policy on Academic Integrity, https://iisc.ac.in/about/student-corner/academic-integrity/ .


### Submission Guidelines
----

1. Copy the **LATEST** template notebook to your local Google drive. Change the name of the notebook to **assignment1_sol.ipynb**. Proceed to complete the assignment within colab.
2. Make edits only in cells and regions that are clearly marked for modification. **Do not change the template in any other way**. We will be automatically parsing relevant cells and functions during grading. If these instructions are not followed (e.g., even an extra space in an unauthorized part), you can get a **zero** for the Assignment.
3. After you've solved the questions, verify that the output that you generate passes the **validation check** of the data types, and matches the reference outputs that are provided for the sample inputs. Note that for **floats**, only the first 3 digits of precision will be checked, but you should not make any changes to the default precision in your code. If the output data type is not valid as specified, you will get a zero for that problem.
4. Each of the problems should take no longer than 5x the time as given for our reference outputs. If it takes longer, the problem will not be evaluated.
5. When you are ready to submit the assignment, download the notebook as a **(.py)** file to your local machine. You can do so by going to **File > Download > Download (.py)** in your colab environment.
6. Place the **assigment1_sol.py** file as **\<IISchandle>_assignment1_sol.py**.<br> **e.g., kautukastu_assigment1_sol.py** if your IISc email address is kautukastu@iisc.ac.in.
7. Upload for submission (.py file) under the **Assignment 1 - Spark Programming** resource on Teams link that will be shared.

## About Common Crawl
-----
The Common Crawl dataset (https://commoncrawl.org/) is a publicly available, petabyte-scale web archive that provides freely accessible web crawl data collected monthly since 2008. It consists of raw web page data, metadata, and text extractions from billions of web pages across multiple languages and domains.

Common Crawl has been instrumental in pretraining models like GPT, BERT, and CLIP by providing vast amounts of textual data. It offers an extensive and diverse snapshot of the internet, making it a valuable resource for training large-scale AI models. Unlike proprietary datasets, it is freely available, enabling research and development without high data collection costs.

With the rise of Large Language Models (LLMs), datasets such as the Common Crawl have gained immense importance. It's been used as the primary source for training LLama.

As the data available in such datasets is vast, raw and unfiltered, preprocessing the data becomes unavoidable before use for training of any AI/LLM models.


## About this Assignment
-----
In this assignment, you will use PySpark to analyze how web content evolves over time using Common Crawl data. The tasks will guide you through loading and cleaning large datasets, tracking keyword and their frequencies, identifying emerging trends, and studying how domains and regions differ in their content focus.

The goal is for you to practice distributed data processing and apply it to a real-world problem of temporal content drift on the web. You will be dealing with Retrieval-Augmented Generation (RAG) as well, where you will think about how modern NLP methods could support large-scale keyword and topic analysis.

### Output Validation
**NOTE:** When we evaluate your assignment, we will sort the output dataframe you return based on specific columns. In each question, we will mention the output column(s) we will sort on. Performing a `diff` on the sorted output dataframe MUST match our *reference outputs* also present in the same sorted order. You *DO NOT* need to perform the sorting when you return the output dataframe. Our test harness will do so.<br>
The expected data type of columns are given in the following format:<br>
`<column_name>: <data_type>`<br>
For example:<br>
`content: string`<br>
means the name of the column is `content` having data type `string`.


### Resources
*    The keywords taken from UN SDG: https://sustainability.utoronto.ca/inventories/sustainable-development-goals-sdgs-keywords/
*    HTML elements/tag reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements

## INITIALIZATION SECTION (DO NOT EDIT)
---
---

### Mount Google Drive
---
"""

#######################################
###!@0.1 START INIT ENVIRONMENT

from google.colab import drive
drive.mount('/content/drive')

### Load necessary files and folders

!mkdir -p /content/data/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/data/cc_tiny.parquet /content/data/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/data/cc_short.parquet /content/data/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/data/stopwords.csv /content/data/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/data/translate.csv /content/data/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/data/keywords.csv /content/data/

!mkdir -p /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans1_1_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans1_2_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans2_1_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans2_2_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans3_1_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans3_2_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans3_3_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans4_1_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans4_2_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans4_3_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans5_1_REF_tiny_output_df.parquet /content/reference_outputs/
!ln -s /content/drive/Shareddrives/DA231o-2025-shared/assignments/assignment1/ReferenceOutputsTiny/ans5_2_REF_tiny_output_df.parquet /content/reference_outputs/

!pip install pyspark
!pip install sentence-transformers
###!@0.1 END INIT ENVIRONMENT

"""### Create spark session
---
"""

#######################################
###!@0.2 START OF PYSPARK INIT

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder.appName("da231o_assignment_1") \
  .config("spark.executor.memory", "10g") \
  .config("spark.driver.memory", "10g") \
  .config("spark.memory.offHeap.enabled", "true") \
  .config("spark.memory.offHeap.size", "10g") \
  .getOrCreate()

  # Spark is ready to go within Colab!
###!@0.2 END OF PYSPARK INIT

"""### Input Data
-----

We have created a subset of Common Crawl data, saving only the relevant fields **(url, date, lang, content)** in a parquet file named `cc_[tiny|short|medium|large].parquet` that is loaded into `input_df` (different input files will be passed to this dataframe variable during the evaluation).

"""

#######################################
###!@0.3 START OF INITIALIZE DATAFRAMES

# NOTE: This code snippet will be replaced during evaluation with the relevant sample input files.
INPUT_DF_SIZE = "tiny"
# INPUT_DF_SIZE = "short"
# INPUT_DF_SIZE = "medium"
# INPUT_DF_SIZE = "large"
input_df = spark.read.parquet("/content/data/cc_"+INPUT_DF_SIZE+".parquet")
input_df.show()

keyword_df = spark.read.csv("/content/data/keywords.csv", header=True)
keyword_df.show()

translate_df = spark.read.csv("/content/data/translate.csv", header=True)
translate_df.show()

stopword_df = spark.read.csv("/content/data/stopwords.csv", header=True)
stopword_df.show()

print(input_df.count())
print(keyword_df.count())
print(translate_df.count())
print(stopword_df.count())

print(input_df.printSchema())
print(keyword_df.printSchema())
print(translate_df.printSchema())
print(stopword_df.printSchema())

###!@0.3 END OF INITIALIZE DATAFRAMES

"""---
---
## YOUR CODE EDITS START HERE

### Common Imports and Functions

List imports and functions that are used across different questions in these sections.
"""

#######################################
###!@0.4 START COMMON USER IMPORTS
#######################################
## Specify valid imports, if any, for ALL your answers  ==========
## start your edits here =================
import math
import time
from sentence_transformers import SentenceTransformer

import re
from pyspark.sql.types import StructField, StructType, StringType, IntegerType, LongType, DoubleType, BooleanType, ArrayType, MapType
from pyspark.sql.functions import udf
from pyspark.sql.window import Window
from pyspark import SparkContext

## end your edits here =================
###!@0.4 END COMMON USER IMPORTS

#######################################
###!@0.5 START COMMON USER FUNCTIONS
#######################################
## Specify user defined functions, if any, used by multiple answers   =====

def generate_embeddings(chunks: list[str]) -> list[list[float]]:
    global model
    if "model" not in globals():
        model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    return model.encode(chunks).tolist()

def cosine_similarity(u, v):
    dot = sum(ui * vi for ui, vi in zip(u, v))
    norm_u = math.sqrt(sum(ui * ui for ui in u))
    norm_v = math.sqrt(sum(vi * vi for vi in v))
    denom = norm_u * norm_v
    return dot / denom if denom != 0 else 0.0

## start your edits here =================

@udf(ArrayType(DoubleType()))
def generate_embeddings_single(chunk: str) -> list[float]:
    global model
    if "model" not in globals():
        model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    return model.encode([chunk]).tolist()[0]

@udf(ArrayType(ArrayType(DoubleType())))
def generate_embeddings_list(chunks: list[str]) -> list[list[float]]:
    global model
    if "model" not in globals():
        model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    return model.encode(chunks).tolist()

@udf(DoubleType())
def similarity_score_topic(topic_emb: list[float], chunks_emb: list[list[float]]):
    score_sum = 0
    for chunk_emb in chunks_emb:
        dot = sum(ui * vi for ui, vi in zip(topic_emb, chunk_emb))
        norm_u = math.sqrt(sum(ui * ui for ui in topic_emb))
        norm_v = math.sqrt(sum(vi * vi for vi in chunk_emb))
        denom = norm_u * norm_v
        score_sum += dot / denom if denom != 0 else 0.0
    return score_sum

def create_regex_from_list(list_str):
  escaped_strings = [re.escape(s) for s in list_str]
  return '|'.join(escaped_strings)

@udf(StringType())
def remove_stopwords(content: str, stopwords_list: list[str], punctuation_pattern: str):
    return "".join(["" if word in stopwords_list else word for word in re.split(punctuation_pattern, content)])

@udf(MapType(StringType(), LongType()))
def count_keywords_month(keywords: list[str], contents: list[str]):
  keyword_counts = {keyword: 0 for keyword in keywords}

  for content in contents:
    for keyword in keywords:
      if keyword in content:
        keyword_counts[keyword] += 1

  return keyword_counts

@udf(MapType(StringType(), LongType()))
def count_keywords_month_lang(keywords: list[str], contents: list[str]):
  keyword_counts = {keyword: 0 for keyword in keywords}

  for keyword in keywords:
    pattern = rf"\b{re.escape(keyword)}\b"
    for content in contents:
        if re.search(pattern, content):
            keyword_counts[keyword] += 1

  return keyword_counts

## end your edits here =================
###!@0.5 END COMMON USER FUNCTIONS

"""### Question 1: Data Preprocessing ***(5+15=20 points)***
----

You will perform certain data cleaning, pre-processing and extractions tasks in this initial question.

#### Question 1.1: Extracting crawl month **(5 points)**
Create a new column `crawl_month: string` by extracting the `YYYY-MM` from the `date: string` column. These will be the focus of your monthly analysis.

**Input:**

`input_df`
*  `uri: string`
*  `lang: string`
*  `date: string`
*  `content: string`

**Output:** Return an output dataframe having the following columns:
*  `uri: string`
*  `lang: string`
*  `date: string`
*  `content: string`
*  `crawl_month: string`
"""

#######################################
###!@1.1 START ANSWER SET 1.1

### Q1.1 ###################################################

def question_1_1(input_df):

  ## start your edits here =================

  output_df = input_df.withColumn("crawl_month", F.substring(F.col("date"), 0, 7))

  ## end your edits here =================

  return output_df

###!@1.1 END ANSWER SET 1.1

"""#### Question 1.2: Content cleanup **(15 points)**

Clean the the `content` column by performing the folloing tasks:
1. Convert all text of content column to lowercase.
2. Remove standard HTML tags.
3. Replace the following escape sequences present as literal in the content column - `\n, \t, \\, \', \", \r, \b, \f, \a` with whitespace.
4. Replace consecutive whitespaces with a single whitespace. Trim leading and trailing whitespaces.
5. Remove stopwords for content in english language (stopwords are given in `stopword_df`).

**Input:** You are given the dataframe from the output of *Q1.1* having following schema:

`input_df`

*  `uri: string`
*  `lang: string`
*  `date: string`
*  `content: string`
*  `crawl_month: string`

`stopword_df`
*  `stopwords`

**Output:** Return an output dataframe that retains some of the input dataframe columns, but with the `content` cleaned up as per the tasks given above. The output DF should have the columns:

*  `uri: string`
*  `lang: string`
*  `crawl_month: string`
*  `content: string`
"""

#######################################
###!@1.2 START ANSWER SET 1.2

### Q1.2 ###################################################

def question_1_2(input_df, stopword_df):

  ## start your edits here =================

  escape_seq = ['\\n', '\\t', '\\r', '\\b', '\\f', '\\a', '\\\\', '\\"', "\\'"]
  escape_seq_reg_expr = create_regex_from_list(escape_seq)
  stopwords_list = stopword_df.select("stopwords").rdd.flatMap(lambda x: x).collect()
  punctuations = [".", ",", "!", "?", ";", ":", "(", ")", "{", "}", "[", "]", "'", '"', "<", ">", "/", " "]
  punctuation_pattern = "([" + "".join(re.escape(c) for c in punctuations) + "])"

  sc = SparkContext.getOrCreate()
  punctuation_pattern = sc.broadcast(punctuation_pattern)
  stopwords_list = sc.broadcast(stopwords_list)

  input_df = input_df.drop("date").withColumn("content", F.lower(F.col("content"))) #lowercase
  input_df = input_df.withColumn("content", F.regexp_replace(F.col("content"), r'<.*?>', " ")) #HTML Tags
  input_df = input_df.withColumn("content", F.regexp_replace(F.col("content"), escape_seq_reg_expr, " ")) # Escape Seqs
  input_df = input_df.withColumn("content", F.trim(F.regexp_replace(F.col("content"), r'\s+', ' '))) # Whitespaces
  en_input_df = input_df.where(F.col("lang") == "en")
  en_input_df = en_input_df.withColumn("content", remove_stopwords(F.col("content"), F.lit(stopwords_list.value), F.lit(punctuation_pattern.value))) # Stopwords
  input_df = input_df.where(F.col("lang") != "en").union(en_input_df)

  output_df = input_df.select("uri", "lang", "crawl_month", "content")

  ## end your edits here =================

  return output_df

###!@1.2 END ANSWER SET 1.2

"""### Question 2: Keyword Identification ***(5+15=20 points)***
----

In this question, you will identify documents that mention specific topics of interest, such as *AI, pandemic, election* and *climate*, that are provided as keywords. This shows how we can detect thematic signals in massive web datasets by matching keywords. It forms the basis for later trend analysis, where we study how the prominence of these topics changes over time.

#### Question 2.1: Filtering documents in English language **(5 points)**
You will first filter the documents to retain only those that contain *English language* content.

**Input:** You are given the dataframe from the output of *Q1.2* having following schema:
*  `uri: string`
*  `lang: string`
*  `crawl_month: string`
*  `content: string`

**Output:** Filter row in the input dataframe to return an output dataframe having content in English language only, with columns:

*  `uri: string`
*  `lang: string`
*  `crawl_month: string`
*  `content: string`
"""

#######################################
###!@2.1 START ANSWER SET 2.1

### Q2.1 ###################################################

def question_2_1(input_df):

  ## start your edits here =================

  output_df = input_df.where(F.col("lang") == "en")

  ## end your edits here =================

  return output_df

###!@2.1 END ANSWER SET 2.1

"""#### Question 2.2: Calculate the frequency of documents for each keyword **(15 points)**
You are given with two dataframes: `input_df (uri, lang, crawl_month, content)` and an additional dataframe `keyword_df (keyword)` having topics of interest. You have to do the following:
1. Count the number of documents containing the given keywords, for each keyword in each month.
2. Compute the normalized frequency of documents containing keyword per month using the formula:<br>
 $normalized\_doc\_count = \frac{Number\_of\_docs\_with\_given\_keyword}{Total\_number\_of\_docs\_in\_that\_month}$<br>

**Note 1:** If a document contains multiple keywords then include that document for computing the count and normalized count for all the keywords present in the document.<br>
**Note 2:** For a given `keyword` and `month`, if no document mentions that keyword in that month then return it's `doc_count` and `normalized_doc_count` as `0`.

**Note 3:** Include subwords for keyword count

**Input:**<br>
`input_df`
*  `uri: string`
*  `lang: string`
*  `crawl_month: string`
*  `content: string`

`keyword_df`
*  `keyword: string`

**Output:** Return a dataframe having the following schema:

*  `keyword: string`
*  `month: string`
*  `doc_count: long`
*  `normalized_doc_count: double`
"""

#######################################
###!@2.2 START ANSWER SET 2.2

### Q2.2 ###################################################

def question_2_2(input_df, keyword_df):

  ## start your edits here =================

  keyword_list = keyword_df.withColumn("keyword", F.lower("keyword")).select("keyword").distinct().rdd.flatMap(lambda x: x).collect()

  input_df = input_df.groupBy("crawl_month").agg(F.count("*").alias("total_docs"),F.collect_list("content").alias("contents")).withColumnRenamed("crawl_month", "month")
  input_df = input_df.withColumn("keywords", F.lit(keyword_list))
  input_df = input_df.withColumn("doc_count_map", count_keywords_month(F.col("keywords"), F.col("contents"))).drop("contents")
  input_df = input_df.select("month", "total_docs", F.explode("doc_count_map").alias("keyword", "doc_count"))
  input_df = input_df.withColumn("normalized_doc_count", F.try_divide("doc_count", "total_docs")).drop("total_docs")

  output_df = input_df.select("keyword", "month", "doc_count", "normalized_doc_count")

  ## end your edits here =================

  return output_df

###!@2.2 END ANSWER SET 2.2

"""### Question 3: Popular, Trending and Emerging Topic Identification ***(15+15+15=45 points)***
----

In this question, you will build upon the normalized keyword statistics from earlier to distinguish between *popular, trending and emerging topics*. These help us understand not just what is being widely discussed, but also what is gaining momentum over time. A description of these trends are:
1. **Popular Topic:** It consistently generates a high volume of interest over a long period. Its defining characteristic is sustained engagement rather than sudden growth.
2. **Trending Topic:** A trending topic experiences a rapid and significant surge in attention, becoming a dominant subject of conversation for a short time. It is defined by its high rate of growth, not necessarily its longevity.
3. **Emerging Topics:** An emerging topic is a subject in the nascent stages of gaining traction, showing an accelerating rate of interest that suggests it may become a trend. It is characterized by its novelty and early-stage growth.

#### Question 3.1: Listing the Popular Topics **(15 points)**
For the given 4-month period `(April-2025 to July-2025)`, you have to identify the popular topics by performing the following tasks:
1. For each `keyword`, compute the average of the `normalized_doc_count` across the time period `(April-2025 to July-2025)` and store it as a column `avg_normalized_doc_count`.
2. Create four new columns, one for each quartile (`0-25`, `26-50`, `51-75`, `76-100`) and classify the `avg_normalized_doc_count` value into one of these four quartiles. You will return this as a "bit vector" row, i.e., for the quartile where the `avg_normalized_doc_count` value of keyword falls, assign the value `true`; for all other quartiles, assign value `false`. **Note:** The data type of quartiles column should be `bool`.

**Input:** You are given the dataframe from the output of *Q2.2* having schema:

*  `keyword: string`
*  `month: string`
*  `doc_count: long`
*  `normalized_doc_count: double`

**Output:** Return an output dataframe having schema:

*  `keyword: string`
*  `avg_normalized_doc_count: double`
*  `25_percentile: bool`
*  `50_percentile: bool`
*  `75_percentile: bool`
*  `100_percentile: bool`
"""

#######################################
###!@3.1 START ANSWER SET 3.1

### Q3.1 ###################################################

def question_3_1(input_df):

  ## start your edits here =================

  months_of_interest = ["2025-04", "2025-05", "2025-06", "2025-07"]

  output_df = input_df.filter(F.col("month").isin(months_of_interest)).groupBy("keyword").agg(F.avg(F.col("normalized_doc_count")).alias("avg_normalized_doc_count"))
  quantiles = output_df.approxQuantile("avg_normalized_doc_count", [0.25, 0.50, 0.75, 1.0], 0)

  output_df = output_df.withColumn("25_percentile", F.col("avg_normalized_doc_count") == 0)
  output_df = output_df.withColumn("50_percentile", (F.col("avg_normalized_doc_count") > 0) & (F.col("avg_normalized_doc_count") <= quantiles[1]))
  output_df = output_df.withColumn("75_percentile", (F.col("avg_normalized_doc_count") > quantiles[1]) & (F.col("avg_normalized_doc_count") <= quantiles[2]))
  output_df = output_df.withColumn("100_percentile", (F.col("avg_normalized_doc_count") > quantiles[2]) & (F.col("avg_normalized_doc_count") <= quantiles[3]))

  ## end your edits here =================

  return output_df

###!@3.1 END ANSWER SET 3.1

"""#### Question 3.2: Listing the Trending Topics **(15 points)**
For each month, you have to identify the trending topics. Consider a topic is trending if its *Rate of Change (ROC)* is greater than or equal to `1` (`100%` more occurrence).

The formula for *Rate of Change (ROC)* for keyword $k$ and month $t$ is:
$ROC_{k,t} = \frac{(normalized\_noc\_nount(k, t) - normalized\_noc\_nount(k, t-1))}{normalized\_doc\_count(k, t-1)}$

where $ROC_{k,t}=0$, if $normalized\_doc\_count(k,t-1)=0$.

If a topic is trending, mark its `trending_flag` as `true`, otherwise `false`.

**Input:** You are given the dataframe from the output of *Q2.2* having schema:

*  `keyword: string`
*  `month: string`
*  `doc_count: long`
*  `normalized_doc_count: double`

**Output:** Return an output dataframe having columns:

*  `keyword: string`
*  `month: string`
*  `ROC: double`
*  `trending_flag: bool`
"""

#######################################
###!@3.2 START ANSWER SET 3.2

### Q3.2 ###################################################

def question_3_2(input_df):

  ## start your edits here =================

  months_order = input_df.select("month").distinct().sort("month").rdd.flatMap(lambda x: x).collect()
  min_month = months_order[0]

  normalized_prev = input_df.where(F.col("month") == min_month).drop("doc_count", "month").withColumnRenamed("normalized_doc_count", "prev_normal")
  output_df = normalized_prev.drop("prev_normal").withColumn("month", F.lit(min_month)).withColumn("ROC", F.lit(0))

  for month in months_order[1:]:
    normalized_curr = input_df.where(F.col("month") == month).drop("doc_count", "month").withColumnRenamed("normalized_doc_count", "curr_normal")
    joined_df = normalized_prev.join(normalized_curr, "keyword", "inner").withColumn("month", F.lit(month))
    joined_df = joined_df.withColumn("ROC", F.try_divide(F.try_subtract("curr_normal", "prev_normal"), "prev_normal"))
    output_df = output_df.union(joined_df.drop("prev_normal", "curr_normal"))
    normalized_prev = normalized_curr.withColumnRenamed("curr_normal", "prev_normal")

  output_df = output_df.fillna({"ROC": 0}).withColumn("trending_flag", F.col("ROC") >= 1)

  ## end your edits here =================

  return output_df

###!@3.2 END ANSWER SET 3.2

"""#### Question 3.3: Identifying the Emerging Topics **(15 points)**
For the 4-month period `(April 2025 to July 2025)`, identify the Emerging Topics. A topic is considered emerging if its rate of change (*ROC*) increases consistently by *0.5* or more in each consecutive month within this 4-month window.

If a topic meets this criterion, set its `emerging_flag` as `true`, and otherwise set it to `false`.<br>

**Input:** You are given the dataframe from the output of *Q3.2* having schema:

*  `keyword: string`
*  `month: string`
*  `ROC: double`
*  `trending_flag: bool`

**Output:** Return an out dataframe having columns:

*  `keyword: string`
*  `emerging_flag: bool`
"""

#######################################
###!@3.3 START ANSWER SET 3.3

### Q3.3 ###################################################

def question_3_3(input_df):

  ## start your edits here =================

    windowSpec = Window.partitionBy("keyword").orderBy("month")
    input_df = input_df.withColumn("prevROC", F.lag(F.col("ROC"), 1, default=0).over(windowSpec))
    input_df = input_df.withColumn("roc_diff_enough", F.when(F.col("ROC") - F.col("prevROC") < 0.5, False).otherwise(True))
    input_df = input_df.groupBy("keyword").agg(F.min("roc_diff_enough").alias("min"), F.max("roc_diff_enough").alias("max"))
    output_df = input_df.withColumn("emerging_flag", F.when((F.col("min") == True) & (F.col("max") == True), True).otherwise(False)).drop("min", "max")

  ## end your edits here =================

    return output_df

###!@3.3 END ANSWER SET 3.2

"""### Question 4: Multilingual Trending and Emerging Topics ***(15+5+10=30 points)***
----

In this question, you will extend the analysis to multilingual web content by using a translation dictionary. The `translate_df` contains a mapping of each keyword into four languages: *English, Spanish, Russian and Japanese*.

#### Question 4.1: Language Filtering and Count **(15 points)**
Steps:
1. From the full pre-processed dataset *(output of Q1.2)*, filter documents written in Spanish, Russian and Japanese language.
2. Convert all the text of content column into lowercase.
3. For each language, compute the `normalized_doc_count` of keywords per month using the translated keywords for respective language from `translate_df`. (Similar to what you did in *Q2.2*)

You can reuse the user-defined functions, if any, from previous questions by defining them in the common function cell above.

**Note:** Do not include subword for count in this case

**Input:** You are provided with two dataframes:<br>

`input_df`

*   `uri: string`
*   `lang: string`
*   `crawl_month: string`
*   `content: string`

`translate_df`

*   `English: string`
*   `Spanish: string`
*   `Japanese: string`
*   `Russian: string`


**Output:** Return a dataframe having schema:

*   `lang: string`
*   `keyword: string`
*   `month: string`
*   `normalized_doc_count: double`
"""

#######################################
###!@4.1 START ANSWER SET 4.1

### Q4.1 ###################################################

def question_4_1(input_df, translate_df):

  langs = ["ja", "es", "ru"]

  keyword_langs_list = {
      "ja": translate_df.select(F.lower("Japanese")).distinct().rdd.flatMap(lambda x: x).collect(),
      "es": translate_df.select(F.lower("Spanish")).distinct().rdd.flatMap(lambda x: x).collect(),
      "ru": translate_df.select(F.lower("Russian")).distinct().rdd.flatMap(lambda x: x).collect()
  }

  output_df = None
  for lang in langs:
      input_df_lang = input_df.filter(F.col("lang") == lang)

      docs_per_month = input_df_lang.groupBy("crawl_month", "lang").agg(F.count("*").alias("total_docs"), F.collect_list("content").alias("contents")).withColumnRenamed("crawl_month", "month")
      input_df_lang = docs_per_month.withColumn("keywords", F.lit(keyword_langs_list[lang]))
      input_df_lang = input_df_lang.withColumn("doc_count_map", count_keywords_month_lang(F.col("keywords"), F.col("contents"))).drop("contents")
      input_df_lang = input_df_lang.select("month", "total_docs", "lang", F.explode("doc_count_map").alias("keyword", "doc_count"))
      input_df_lang = input_df_lang.withColumn("normalized_doc_count", F.try_divide("doc_count", "total_docs")).drop("total_docs", "doc_count")

      if output_df is None:
          output_df = input_df_lang
      else:
          output_df = input_df_lang.union(output_df)

  output_df = output_df.select("lang", "keyword", "month", "normalized_doc_count")

  ## end your edits here =================

  return output_df

###!@4.1 END ANSWER SET 4.1

"""#### Question 4.2: Emerging Topics **(5 points)**

For each new language (Spanish, Russian and Japanese), identify the emerging topics over the period of 4-months `(April-2025 to July-2025)`. This follows the same logic as given in *Q3.3*.

**Note:** You can reuse the user defined function, if any, from previous questions.

**Input:** You are given the output dataframe from *Q4.1* having following schema:
*   `lang: string`
*   `keyword: string`
*   `month: string`
*   `normalized_doc_count: double`

**Output:** Return an dataframe having schema:

*   `lang: string`
*   `keyword: string`
*   `emerging_flag: bool`
"""

#######################################
###!@4.2 START ANSWER SET 4.2

### Q4.2 ###################################################

def question_4_2(input_df):

  ## start your edits here =================

  months_of_interest = ["2025-04", "2025-05", "2025-06", "2025-07"]

  roc_df = input_df.where(F.col("month") == months_of_interest[0]).drop("normalized_doc_count").withColumn("ROC", F.lit(0))
  normalized_prev = input_df.where(F.col("month") == months_of_interest[0]).drop("month").withColumnRenamed("normalized_doc_count", "prev_normal")

  for month in months_of_interest[1:]:
    normalized_curr = input_df.where(F.col("month") == month).drop("month").withColumnRenamed("normalized_doc_count", "curr_normal")
    joined_df = normalized_prev.join(normalized_curr, ["lang", "keyword"], "inner").withColumn("month", F.lit(month))
    joined_df = joined_df.withColumn("ROC", F.try_divide(F.try_subtract("curr_normal", "prev_normal"), "prev_normal"))
    roc_df = roc_df.union(joined_df.drop("prev_normal", "curr_normal"))
    normalized_prev = normalized_curr.withColumnRenamed("curr_normal", "prev_normal")

  roc_df = roc_df.fillna({"ROC": 0})

  windowSpec = Window.partitionBy("lang", "keyword").orderBy("month")
  roc_df = roc_df.withColumn("prevROC", F.lag(F.col("ROC"), 1, default=0).over(windowSpec))
  roc_df = roc_df.withColumn("roc_diff_enough", F.when(F.col("ROC") - F.col("prevROC") < 0.5, False).otherwise(True))
  roc_df = roc_df.groupBy("lang", "keyword").agg(F.min("roc_diff_enough").alias("min"), F.max("roc_diff_enough").alias("max"))
  output_df = roc_df.withColumn("emerging_flag", F.when((F.col("min") == True) & (F.col("max") == True), True).otherwise(False)).drop("min", "max")

  ## end your edits here =================

  return output_df

###!@4.2 END ANSWER SET 4.2

"""#### Question 4.3: Globally Emerging Topics **(10 points)**
So far, you have identified emerging topics in four different languages. Now, you can detect globally emerging topic. You will be provided the DataFrame of emerging topics in English *(output of Q3.3)*, the emerging topics in the other three languages *(output of Q4.2)* and the `translate_df`. Identify those keywords that are emerging across all four languages (English, Spanish, Russian and Japanese).

**Input:** You are given the output dataframe of the *Q3.3* (`input_df_eng_lang`), *Q4.2* (`input_df_3_lang`) and `translate_df` having the following schema:

`input_df_eng_lang`

*  `keyword: string`
*  `emerging_flag: bool`

`input_df_3_lang`

*   `lang: string`
*   `keyword: string`
*   `emerging_flag: bool`

`translate_df`

*   `English: string`
*   `Spanish: string`
*   `Japanese: string`
*   `Russian: string`

**Output:** Return a dataframe having single column named `globally_emerging_topics: string`, returning the globally emerging keywords across all four languages. The keyword should be returned in its the English language form.
"""

#######################################
###!@4.3 START ANSWER SET 4.3

### Q4.3 ###################################################

def question_4_3(input_df_eng_lang, input_df_3_lang, translate_df):

  ## start your edits here =================

  emerging_en_df = input_df_eng_lang.withColumn("lang", F.lit("en")).select("lang", "keyword", "emerging_flag")
  emerging_full_df = emerging_en_df.union(input_df_3_lang)
  emerging_true_full = emerging_full_df.filter(F.col("emerging_flag") == True).drop("emerging_flag")

  lang_map = {
      "es": "Spanish",
      "ru": "Russian",
      "ja": "Japanese"
  }

  rows = emerging_true_full.filter(F.col("lang") == "en").select("keyword").rdd.flatMap(lambda x: x).collect()
  for lang in ["es", "ja", "ru"]:
      rows.extend(emerging_true_full.filter(F.col("lang") == lang).select("keyword").withColumnRenamed("keyword", lang_map[lang]).join(translate_df.select(lang_map[lang], "English"), on=lang_map[lang]).select("English").rdd.flatMap(lambda x: x).collect())

  output_df = spark.createDataFrame([(row,) for row in rows], "globally_emerging_topics: string").distinct()

  ## end your edits here =================

  return output_df

###!@4.3 END ANSWER SET 4.3

"""### Question 5: Search Engine using Retrieval ***(10+25=35 points)***
----

##Background

Large Language Models (LLMs) are powerful but have inherent limitations, including knowledge cutoffs (outdated information), a tendency to *hallucinate* facts, and a lack of source verifiability. Retrieval-Augmented Generation (RAG) is an architectural approach that mitigates these weaknesses by connecting the LLM to an external knowledge base. A typical RAG pipeline operates in three stages:<br>

* Retrieve: Relevant documents are fetched from a knowledge base in response to a query.
* Augment: The retrieved documents are inserted into the LLM's prompt, providing it with relevant context.
* Generate: The LLM generates an answer based on the augmented prompt.

Retrieving relevant data from a knowledge base involves the following components:
* Embedding Models: Converts text into numerical vectors that capture semantic meaning.
* Vector Databases: Store document chunks and their embeddings, enabling similarity-based retrieval.
* Similarity Search: Finds the most relevant documents by comparing vector representations.

In this question, you will focus on implementing the retrieval component of a RAG pipeline. Your task is to design and build a vector search mechanism using PySpark. Using the emerging keywords identified in the previous question, you must efficiently search and retrieve the most relevant urls for each keyword.

---

#### Question 5.1: Prepare Vector Store **(10 points)**

Work with the given dataset `input_df` to prepare for a vector store using Spark Dataframes. For each of the web `content`, preprocess the text by splitting it into smaller *chunks* using a simple chunking logic implemented as follows. The content belonging to each `uri` will be splitted into chunks, such that the first chunk has the *first 256 characters*, the second chunk has the next *256 characters* and so on until the last chunk that has *at most* 256 characters. <br>

Webpages often contain large volumes of text, making it computationally expensive to generate embeddings for all content. To address this, we limit the chunks to at most 5 chunks that are evenly distributed across the content. The chunk selection logic is as follows:

* If a webpage has 5 or fewer chunks, include all of them.
* If a webpage has more than 5 chunks, select exactly 5 using the formula


$$
\text{index}_i = \left\lfloor \frac{i \times n}{5} \right\rfloor
$$

where:
- **i** in \{0,1,2,3,4\} is the position of the selected chunk.
- **n** is the total number of chunks in the document.

**Suggestion** use user defined functions, UDFs to implement the solution


**Input:**
The input to the question is a dataframe `input_df` which is the output of Questions `2.1`. The `input_df` has the following schema :

`input_df`
* `uri: string`
* `lang: string`
* `crawl_month: string`
* `content: string`

**Output:**
Output a single dataframe that contains two columns `uri` and `chunks` where `chunks` contains the list of sampled chunks for that uri.

`output_df`
* `uri: string`
* `chunks: array<string>`
"""

#######################################
###!@5.1 START ANSWER SET 5.1

### Q5.1 ###################################################

def question_5_1(input_df):

  ## start your edits here =================

  chunk_length = 256
  max_chunks = 5
  output_df = input_df.withColumn("total_chunks", F.ceil(F.try_divide(F.length(F.col("content")), F.lit(chunk_length))))

  columns = []
  for i in range(max_chunks):
      columns.append(f"chunk_{i}")
      output_df = output_df.withColumn(f"chunk_{i}", F.substr(F.col("content"), F.try_add(F.try_multiply(F.floor(F.try_divide(F.try_multiply(F.lit(i), F.col("total_chunks")), F.lit(max_chunks))), F.lit(chunk_length)), F.lit(1)), F.lit(chunk_length)))

  output_df = output_df.withColumn("chunks", F.array_distinct(F.array(columns))).drop(*columns, "total_chunks", "lang", "content", "crawl_month")

  ## end your edits here =================

  return output_df

###!@5.1 END ANSWER SET 5.1

"""#### Question 5.2: Vector Search Engine **(25 points)**

In this question, you need to return the 5 most relevant `uri` for each of the `globally_emerging_topics` acquired previously using a simple similarity search on their embeddings.  

Given the `input_df`from the previous question and the `globally_emerging_topics` from question `4.3`, generate the embeddings for each of the chunks and each of topics using the embedding model `all-MiniLM-L6-v2` loaded from hugging face `sentence_transformers` library [link](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2). <br><br>


You can now find how relevant a `uri` is for any `topic` present in `globally_emerging_topics` by using a similarity search algorithm. Use the *cosine similarity* between the embedding of the *chunk* and the embedding of the *topic* to find the similarity score between them. Find the `score` for the `uri` for that particular `topic` by adding the similarity scores of all the chunks belonging to it. Finally, return the top 5 `uri` with the highest `score` along with their `rank`. Where for a `topic`, `uri` with the highest `score` would be ranked `1`, `uri` with the second highest score would be ranked `2` and so on.



The *Cosine similarity* between two vectors $\mathbf{u}$ and $\mathbf{v}$ is defined as:<br><br>

$$
\operatorname{cosine\_similarity}(\mathbf{u}, \mathbf{v}) = \frac{\mathbf{u} \cdot \mathbf{v}}{\Vert\mathbf{u}\Vert \, \Vert\mathbf{v}\Vert}$$

- $\mathbf{u} \cdot \mathbf{v}$ is the **dot product** of the two vectors.  
- $\|\mathbf{u}\|$ and $\|\mathbf{v}\|$ are their **Euclidean norms** (vector lengths).  
- The value is always between **-1 and 1**:
- **1** means same direction (high similarity)  
- **0** means orthogonal (no similarity)  
- **-1** means opposite direction (opposite meaning)  
<br>

Code for generating the embeddings and the cosine similarity is provided in the common imports and functions cell.

**Note:** If the globally_emerging_topic dataframe contains less than 3 records then initialize it with the following topics :<br>
`AI`, `5G`,`sustainable development`

**Suggestion** Make use of user defined functions (UDF) to use the embedding model as well as the cosine function


**Input:**
The input to the question is a dataframe `input_df` which is the output of Questions `5.1` and `globally_emerging_topics` which is the output of Question `4.3`. The `input_df` has the following schema :

`input_df`
* `uri: string`
* `chunks: array<string>`

`globally_emerging_topics_df`
* `globally_emerging_topics: string`

**Output:**
Output a single dataframe that contains the columns `topic`, `rank` and `uri`. The `output_df` has the following schema.

`output_df`
* `topic: string`
* `rank: integer`
* `uri: string`



"""

#######################################
###!@5.2 START ANSWER SET 5.2

### Q5.2 ###################################################

def question_5_2(input_df, globally_emerging_topics_df):

  ## start your edits here =================

  dummy_topics = ["AI", "5G", "sustainable development"]
  if globally_emerging_topics_df.count() < 3:
      globally_emerging_topics_df = spark.createDataFrame([(topic, ) for topic in dummy_topics], schema="globally_emerging_topics: string")

  topics_emb = globally_emerging_topics_df.distinct().withColumn("topic_emb", generate_embeddings_single(F.col("globally_emerging_topics")))
  uri_chunks_emb = input_df.withColumn("chunks_emb", generate_embeddings_list(F.col("chunks"))).drop("chunks")

  topics_emb_map = {row["globally_emerging_topics"]: row["topic_emb"] for row in topics_emb.collect()}
  topics_emb_map_str_list = [f"{key}:{topics_emb_map[key]}" for key in topics_emb_map.keys()]

  sc = SparkContext.getOrCreate()
  topics_emb_map_str_list = sc.broadcast(topics_emb_map_str_list)
  uri_chunks_emb = uri_chunks_emb.withColumn("topic_emb_map_str", F.lit(topics_emb_map_str_list.value))
  topic_emb_split_col = F.split("topic_emb_map", ":")
  uri_chunks_emb = uri_chunks_emb.select("*", F.explode("topic_emb_map_str").alias("topic_emb_map"), topic_emb_split_col.getItem(0).alias("topic"), topic_emb_split_col.getItem(1).alias("topic_emb"))
  uri_chunks_emb = uri_chunks_emb.withColumn("topic_emb", F.from_json(F.col("topic_emb"), ArrayType(DoubleType()))).drop("topic_emb_map", "topic_emb_map_str")
  uri_topic_score = uri_chunks_emb.withColumn("score", similarity_score_topic(F.col("topic_emb"), F.col("chunks_emb"))).drop("topic_emb", "chunks_emb")

  windowSpec = Window.partitionBy("topic").orderBy(F.col("score").desc())
  ranked_df = uri_topic_score.withColumn("rank", F.rank().over(windowSpec))
  output_df = ranked_df.filter(F.col("rank") <= 5).sort(F.col("rank")).drop("score")
  output_df = output_df.select("topic", "rank", "uri")

  ## end your edits here =================

  return output_df

###!@5.2 END ANSWER SET 5.2

"""---
---
### YOUR CODE EDITS END HERE
---
---

## VALIDATION HARNESS
---
---

### Sanity Check of Schema of Output Dataframes
---
"""

###!@6.1 START SANITY CHECK OF DATA TYPES
# ========== *** DO NOT MODIFY *** ========== #

from pyspark.sql import DataFrame

def get_reference_df(question: str, input_data_size: str) -> DataFrame:
    # This functions returns the correct dataframe for a given question and dataset size
    mapping = {
        ("ans1_1", "tiny"):  "ans1_1_REF_tiny_output_df.parquet",
        ("ans1_1", "small"): "ans1_1_REF_small_output_df.parquet",
        ("ans1_2", "tiny"):  "ans1_2_REF_tiny_output_df.parquet",
        ("ans1_2", "small"): "ans1_2_REF_small_output_df.parquet",
        ("ans2_1", "tiny"):  "ans2_1_REF_tiny_output_df.parquet",
        ("ans2_1", "small"): "ans2_1_REF_small_output_df.parquet",
        ("ans2_2", "tiny"):  "ans2_2_REF_tiny_output_df.parquet",
        ("ans2_2", "small"): "ans2_2_REF_small_output_df.parquet",
        ("ans3_1", "tiny"):  "ans3_1_REF_tiny_output_df.parquet",
        ("ans3_1", "small"): "ans3_1_REF_small_output_df.parquet",
        ("ans3_2", "tiny"):  "ans3_2_REF_tiny_output_df.parquet",
        ("ans3_2", "small"): "ans3_2_REF_small_output_df.parquet",
        ("ans3_3", "tiny"):  "ans3_3_REF_tiny_output_df.parquet",
        ("ans3_3", "small"): "ans3_3_REF_small_output_df.parquet",
        ("ans4_1", "tiny"):  "ans4_1_REF_tiny_output_df.parquet",
        ("ans4_1", "small"): "ans4_1_REF_small_output_df.parquet",
        ("ans4_2", "tiny"):  "ans4_2_REF_tiny_output_df.parquet",
        ("ans4_2", "small"): "ans4_2_REF_small_output_df.parquet",
        ("ans4_3", "tiny"):  "ans4_3_REF_tiny_output_df.parquet",
        ("ans4_3", "small"): "ans4_3_REF_small_output_df.parquet",
        ("ans5_1", "tiny"):  "ans5_1_REF_tiny_output_df.parquet",
        ("ans5_1", "small"): "ans5_1_REF_small_output_df.parquet",
        ("ans5_2", "tiny"):  "ans5_2_REF_tiny_output_df.parquet",
        ("ans5_2", "small"): "ans5_2_REF_small_output_df.parquet",
    }

    try:
        path = mapping[(question, input_data_size)]
    except KeyError:
        raise Exception(f"Invalid question={question} and dataset size={input_data_size}")

    base_path = "/content/reference_outputs/"

    return spark.read.parquet(base_path+path)


def checkDF(question: str, input_data_size: str, user_output: DataFrame) -> bool:
    ref_df = get_reference_df(question, input_data_size)

    ref_schema = [(f.name, f.dataType) for f in ref_df.schema.fields]
    user_schema = [(f.name, f.dataType) for f in user_output.schema.fields]

    # Schema check
    if ref_schema != user_schema:
        print("Schema mismatch")
        print("Expected schema: ")
        ref_df.printSchema()
        print("Your schema:")
        user_output.printSchema()
        return False

    # Number of Records check
    if ref_df.count() != user_output.count():
        print("Number of Records mismatch")
        return False

    # Difference in row content check (ignoring the order of records)
    diff1 = ref_df.subtract(user_output).count()
    diff2 = user_output.subtract(ref_df).count()

    if diff1 == 0 and diff2 == 0:
        return True
    else:
        print("Row content mismatch")
        return False

###!@6.1 END SANITY CHECK OF DATA TYPES

"""### Evaluation Harness Section
---

You will execute this code section to run the solution function for each of the questions. In this section, each output dataframe from the previous question is passed to the next question's function as an input. So, ensure that you DO NOT MODIFY the arguments being passed to the function for each question and must solve them in the given order.
"""

###!@6.2 START ANSWER SET EVALUATION
# ========== *** DO NOT MODIFY *** ========== #

ans1_1_output_df = question_1_1(input_df)
# ans1_1_output_df.show()
print('answer 1_1: ', checkDF("ans1_1", INPUT_DF_SIZE, ans1_1_output_df))
ans1_1_output_df.write.mode("overwrite").parquet("ans1_1_output_df.parquet")

ans1_2_output_df = question_1_2(ans1_1_output_df, stopword_df)
# ans1_2_output_df.show()
print('answer 1_2: ', checkDF("ans1_2", INPUT_DF_SIZE, ans1_2_output_df))
ans1_2_output_df.write.mode("overwrite").parquet("ans1_2_output_df.parquet")

ans2_1_output_df = question_2_1(ans1_2_output_df)
# ans2_1_output_df.show()
print('answer 2_1: ', checkDF("ans2_1", INPUT_DF_SIZE, ans2_1_output_df))
ans2_1_output_df.write.mode("overwrite").parquet("ans2_1_output_df.parquet")

ans2_2_output_df = question_2_2(ans2_1_output_df, keyword_df)
# ans2_2_output_df.show()
print('answer 2_2: ', checkDF("ans2_2", INPUT_DF_SIZE, ans2_2_output_df))
ans2_2_output_df.write.mode("overwrite").parquet("ans2_2_output_df.parquet")

ans3_1_output_df = question_3_1(ans2_2_output_df)
# ans3_1_output_df.show()
print('answer 3_1: ', checkDF("ans3_1", INPUT_DF_SIZE, ans3_1_output_df))
ans3_1_output_df.write.mode("overwrite").parquet("ans3_1_output_df.parquet")

ans3_2_output_df = question_3_2(ans2_2_output_df)
# ans3_2_output_df.show()
print('answer 3_2: ', checkDF("ans3_2", INPUT_DF_SIZE, ans3_2_output_df))
ans3_2_output_df.write.mode("overwrite").parquet("ans3_2_output_df.parquet")

ans3_3_output_df = question_3_3(ans3_2_output_df)
# ans3_3_output_df.show()
print('answer 3_3: ', checkDF("ans3_3", INPUT_DF_SIZE, ans3_3_output_df))
ans3_3_output_df.write.mode("overwrite").parquet("ans3_3_output_df.parquet")

ans4_1_output_df = question_4_1(ans1_2_output_df, translate_df)
# ans4_1_output_df.show()
print('answer 4_1: ', checkDF("ans4_1", INPUT_DF_SIZE, ans4_1_output_df))
ans4_1_output_df.write.mode("overwrite").parquet("ans4_1_output_df.parquet")

ans4_2_output_df = question_4_2(ans4_1_output_df)
# ans4_2_output_df.show()
print('answer 4_2: ', checkDF("ans4_2", INPUT_DF_SIZE, ans4_2_output_df))
ans4_2_output_df.write.mode("overwrite").parquet("ans4_2_output_df.parquet")

ans4_3_output_df = question_4_3(ans3_3_output_df,ans4_2_output_df, translate_df)
# ans4_3_output_df.show()
print('answer 4_3: ', checkDF("ans4_3", INPUT_DF_SIZE, ans4_3_output_df))
ans4_3_output_df.write.mode("overwrite").parquet("ans4_3_output_df.parquet")

ans5_1_output_df = question_5_1(ans2_1_output_df)
# ans5_1_output_df.show()
print('answer 5_1: ', checkDF("ans5_1", INPUT_DF_SIZE, ans5_1_output_df))
ans5_1_output_df.write.mode("overwrite").parquet("ans5_1_output_df.parquet")

ans5_2_output_df = question_5_2(ans5_1_output_df, ans4_3_output_df)
# ans5_2_output_df.show()
print('answer 5_2: ', checkDF("ans5_2", INPUT_DF_SIZE, ans5_2_output_df))
ans5_2_output_df.write.mode("overwrite").parquet("ans5_2_output_df.parquet")

# ========== *** DO NOT MODIFY *** ========== #
###!@6.2 END ANSWER SET EVALUATION